export const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  GET_PRODUCTS: 'GET_PRODUCTS',
  UPDATE_CART: 'UPDATE_CART',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  RESET_CHECKOUT: 'RESET_CHECKOUT',
}
